### PR TITLE
Export DropdownOptionProps interface

### PR DESCRIPTION
**Pull request by natalynyu**
This `DropdownOptionProps` interface is being exported so that it can be used in Course Planner.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality
      to change)

## Checklist:

- [x] I have run `eslint` on the code
- [ ] I have added JSDoc for all of my code (where applicable)
- [ ] I have added tests to cover my changes.

## Priority:
- [x] Normal 
- [ ] High 

## Related Issues:

Related to: [#532](https://github.com/seas-computing/course-planner/issues/532)

### CODE REVIEW

**Comment by natalynyu** [comment]
> This looks great, but I think we might also want to include this interface in [the `export` statement in `src/Forms/index.ts`](https://github.com/seas-computing/mark-one/blob/88d27f1e61ea2f715b69684df089ed5ca0c17105/src/Forms/index.ts#L3) in order for it to be importable.

I'm not sure that we have to export from `index.ts` for these interfaces, because for instance, `DropdownProps` is available for importing in Course Planner, but it's not being exported in `index.ts`:
image

**Comment by rmainseas** [comment]
Valid point. That's interesting...in my testing - I had to add `DropdownOptionProps` to `index.ts` in order for it to be importable.

**Comment by rmainseas** [comment]
Valid point. That's interesting...in my testing - I had to add `DropdownOptionProps` to `index.ts` in order for it to be importable.

**Comment by natalynyu** [comment]
@rmainseas Makes total sense now! I originally thought it was a technical issue. I exported the two interfaces `DropdownProps` and `DropdownOptionProps` from `index.ts` so that we can import directly from `mark-one.` Thanks!

**Comment by rmainseas** [comment]
Anyway...this looks great now so I'm going to approve it.

**Review by rmainseas — APPROVED** [review]

**Pull request merged**
